"""
Report Generator
-----------------
This is the single highest-value feature for a public-facing security
platform: it turns raw scan output into a client-deliverable report.
This is what separates "script that pings ports" from "tool."

Generates a styled HTML report (opens in any browser, prints to PDF
natively). If `weasyprint` is installed, also emits a true PDF.
"""

import os
import time
import json

REPORTS_DIR = os.path.join(os.path.dirname(__file__), "..", "reports")

HTML_TEMPLATE = """<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Ghost OS Security Report — {target}</title>
<style>
  body {{ font-family: 'Segoe UI', system-ui, sans-serif; background: #0b0e14; color: #d6e0f0; margin: 0; padding: 40px; }}
  .header {{ border-bottom: 2px solid #2dd4bf; padding-bottom: 16px; margin-bottom: 24px; }}
  h1 {{ color: #2dd4bf; margin: 0; font-size: 28px; }}
  .meta {{ color: #7a8aa3; font-size: 13px; margin-top: 6px; }}
  .section {{ background: #131722; border: 1px solid #232a3b; border-radius: 8px; padding: 20px; margin-bottom: 16px; }}
  .section h2 {{ color: #2dd4bf; font-size: 16px; margin-top: 0; }}
  pre {{ background: #0b0e14; padding: 12px; border-radius: 6px; overflow-x: auto; color: #a7f3d0; font-size: 13px; }}
  .badge {{ display: inline-block; background: #1e2937; color: #2dd4bf; padding: 3px 10px; border-radius: 12px; font-size: 12px; margin-right: 6px; }}
  footer {{ margin-top: 32px; color: #4a5568; font-size: 11px; border-top: 1px solid #232a3b; padding-top: 12px; }}
</style>
</head>
<body>
  <div class="header">
    <h1>Ghost OS — Security Assessment Report</h1>
    <div class="meta">Target: {target} &nbsp;|&nbsp; Analyst: {analyst} &nbsp;|&nbsp; Generated: {timestamp}</div>
  </div>

  <div class="section">
    <h2>Scope &amp; Authorization</h2>
    <span class="badge">Lab Target</span><span class="badge">Consent Logged</span>
    <p>This assessment was performed under explicit, logged authorization against a
    pre-approved lab/demo target. See the audit trail for consent and action history.</p>
  </div>

  <div class="section">
    <h2>Findings</h2>
    <pre>{findings_json}</pre>
  </div>

  <footer>
    Generated by Ghost OS Zero Trust Edition. This report is for authorized
    security testing and educational purposes only. See LEGAL.md.
  </footer>
</body>
</html>
"""


def generate_report(target: str, findings: dict, analyst: str = "unknown") -> str:
    os.makedirs(REPORTS_DIR, exist_ok=True)
    timestamp = time.strftime("%Y-%m-%d %H:%M:%S UTC", time.gmtime())
    safe_target = "".join(c if c.isalnum() else "_" for c in target) or "report"
    filename = f"{safe_target}_{int(time.time())}.html"
    path = os.path.join(REPORTS_DIR, filename)

    html = HTML_TEMPLATE.format(
        target=target,
        analyst=analyst,
        timestamp=timestamp,
        findings_json=json.dumps(findings, indent=2),
    )

    with open(path, "w") as f:
        f.write(html)

    # Optional: emit a real PDF too, if weasyprint is available
    try:
        from weasyprint import HTML
        pdf_path = path.replace(".html", ".pdf")
        HTML(string=html).write_pdf(pdf_path)
        return pdf_path
    except ImportError:
        return path
